# Generated by Django 3.1 on 2022-11-22 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='Variation_category',
            new_name='variation_category',
        ),
    ]
